import joblib
import streamlit as st
import numpy as np
import pandas as pd


st.title("Hindistandaki ikinciel Araç Fiyat Tahmin Uygulamsı")


@st.cache_resource
def load_model():
    return joblib.load("xgb_model.pkl")

model = load_model()

car_age = st.number_input("Car Age: ", min_value = 0, value = 30)
km = st.number_input("km: ", min_value = 0, value = 50000)
km_year = km / max(car_age, 1)
marka_model = st.text_input("Marka Model: ", value = "Honda City")
Length = st.number_input("Length: ", min_value = 2700, max_value = 6000)
Width = st.number_input("Width: ", min_value = 1312, max_value = 2240)
Height = st.number_input("Height: ", min_value = 1160, max_value = 2080)
Wheel_Base = st.number_input("Wheel_Base: ", min_value = 1840, value = 3772)
Seats = st.number_input("Seats: ", min_value = 1, max_value = 5)
Max_Power = st.number_input("Max_Power: ", min_value = 11, max_value = 780)
Max_Torque = st.number_input("Max_Torque: ", min_value = 5, max_value = 900)
fuel = st.selectbox("Fuel", ["cng", "lpg", "electric", "diesel", "petrol"])
transmission = st.selectbox("Transmission", ['manual', 'automatic'])
body = st.selectbox("Body", ['hatchback', 'sedan', 'muv', 'minivans','pickup trucks', 'suv','luxury vehicles', 'convertibles', 'coupe', 'wagon', 'hybrids'])
City = st.selectbox("City", [
 'lucknow', 'mumbai', 'new delhi', 'gurgaon', 'pune', 'agra', 'ghaziabad',
 'bangalore', 'ludhiana', 'guwahati', 'kanpur', 'mira road', 'sonipat', 'thane',
 'dharuhera', 'noida', 'nashik', 'aurangabad', 'rajkot', 'navsari',
 'ranga reddy', 'bathinda', 'chandigarh', 'behror', 'porbandar', 'amreli',
 'ankleshwar', 'budaun', 'ahmednagar', 'allahabad', 'aligarh', 'kengeri',
 'visnagar', 'greater noida', 'morbi', 'sahibabad', 'latur', 'gandhinagar',
 'ahmedabad', 'jaipur', 'dewas', 'meerut', 'patna', 'faridabad', 'bhojpur',
 'bhopal', 'vadodara', 'vasai', 'varanasi', 'ulhasnagar', 'rajahmundry',
 'azamgarh', 'bareilly', 'bhadohi', 'junagadh', 'bulandshahr', 'bikaner',
 'rewari', 'kota', 'panipat', 'alwar', 'dhule', 'machilipatnam', 'jalalabad',
 'amroha', 'gaya', 'vijapur', 'dahanu', 'indore', 'bhiwadi', 'safidon', 'bardoli',
 'rupnagar', 'vapi', 'baghpat', 'nanded', 'satara', 'gorakhpur', 'sampla',
 'jamnagar', 'mathura', 'agartala', 'bijnor', 'barwala', 'rampur',
 'visakhapatnam', 'anand', 'solan', 'silvassa', 'gonda', 'pratapgarh', 'bharuch',
 'rohtak', 'mahendragarh', 'sirsa', 'hyderabad', 'shamli', 'ayodhya', 'jhalawar',
 'bhiwandi', 'mehsana', 'bhubaneswar', 'gwalior', 'shahjahanpur', 'navi mumbai',
 'panvel', 'hapur', 'auraiya', 'moradabad', 'jhajjar', 'hisar', 'nellore',
 'palwal', 'jagdalpur', 'jind', 'kolhapur', 'udaipur', 'narsapur', 'balaghat',
 'bavla', 'vijayawada', 'pimpri chinchwad', 'bhavnagar', 'zirakpur', 'etawah',
 'chennai', 'surat', 'kochi', 'nagpur', 'dehradun', 'coimbatore', 'sagar',
 'nizamabad', 'rayagada', 'nasirabad', 'banda', 'belgaum', 'sri muktsar sahib',
 'mainpuri', 'mangalore', 'paschim medinipur', 'west tripura', 'jammu',
 'dharmavaram', 'ramachandrapuram', 'lakhimpur kheri', 'srinagar', 'fatehabad',
 'kachchh', 'jaunpur', 'fatehpur', 'chittorgarh', 'sinnar', 'kurnool', 'ujjain',
 'ratnagiri', 'kolkata', 'warangal', 'hubli', 'kharghar', 'begusarai', 'neemuch',
 'hazaribagh', 'bijapur', 'ranchi', 'salem', 'solapur', 'barhalganj', 'valsad',
 'ramanathapuram', 'srikalahasti', 'yamuna nagar', 'bokaro', 'hoshiarpur',
 'chattarpur', 'madhyamgram', 'sheikhpura', 'purnia', 'jhansi',
 'thiruvananthapuram', 'madurai', 'alipurduar', 'badlapur', 'amritsar',
 'gulbarga', 'jamshedpur', 'jabalpur', 'durgapur', 'jodhpur', 'haldwani',
 'tenali', 'pudukkottai', 'hamirpur(up)', 'hosur', 'ramanagara', 'parbhani',
 'bharatpur', 'palamu', 'hajipur', 'guntur', 'puri', 'bhilai', 'shimoga',
 'shahdol', 'raigarh', 'vaishali', 'sri ganganagar', 'bilaspur', 'purulia',
 'bodeli', 'dahod', 'byasanagar', 'goa', 'kharagpur', 'ghazipur', 'haridwar',
 'nagaur', 'east godavari', 'jharsuguda', 'churu', 'hoshangabad', 'faizabad',
 'firozabad', 'mysore', 'anuppur', 'kapurthala', 'jhunjhunu', 'ambala', 'khair',
 'ballabhgarh', 'ongole', 'kaithal', 'raipur', 'verna', 'sikar', 'firozpur',
 'patiala', 'ambikapur', 'dhrangadhra', 'palghar', 'amb', 'karauli', 'satna',
 'raigad', 'sitapur', 'nandurbar', 'surendranagar', 'sonbhadra', 'balrampur',
 'secunderabad', 'muzaffarnagar', 'surajpur', 'hooghly', 'bidar', 'rudrapur',
 'agar malwa', 'shirdi', 'yavatmal', 'muzaffarpur', 'korba', 'betul', 'guna',
 'barnala', 'ratlam', 'buldhana', 'dibrugarh', 'gandhidham', 'rajim',
 'udham singh nagar', 'khopoli', 'singrauli', 'dombivli', 'manesar',
 'kanpur dehat', 'daman', 'ernakulam', 'vizianagaram', 'karwar',
 'neem-ka-thana', 'bapatla', 'ballia', 'dhanbad', 'narwana', 'sattenapalli',
 'malkangiri', 'mandi', 'jalgaon', 'fazilka', 'medak district', 'karnal',
 'deoghar', 'una', 'dalkhola', 'koppal', 'nadia', 'hathras', 'kalyan', 'sangli',
 'jangaon', 'khammam', 'lalitpur', 'berhampur', 'kakinada', 'ambedkar nagar',
 'bhind', 'jalandhar', 'virar', 'amethi', 'thrissur', 'baran', 'harur',
 'sawai madhopur', 'west godavari', 'akola', 'gokak', 'south 24 parganas',
 'haldia', 'amravati', 'bhilwara', 'kolar', 'gangapur city', 'pali', 'kottayam',
 'hanumangarh', 'miraj', 'asansol', 'panna', 'angul', 'siliguri', 'chittoor',
 'bhagalpur', 'kollam', 'maldah', 'katni', 'boisar', 'krishnagiri', 'jalpaiguri',
 'chandauli', 'jashpur', 'bellary', 'koraput', 'jam jodhpur', 'tiruchengode',
 'mandsaur', 'tiruppur', 'pathanamthitta', 'shillong', 'nohar', 'kannauj',
 'kheda', 'bandipora', 'raebareli', 'poonch', 'rewa', 'pulwama', 'guruvayoor',
 'itanagar', 'vellore', 'patan', 'vashi', 'madanganj', 'lakhisarai', 'bardhaman',
 'mahoba', 'east sikkim', 'bankura', 'beawar', 'hamirpur(hp)', 'dharwad',
 'kharar', 'shimla', 'mohali', 'kurukshetra', 'sasaram', 'raiganj', 'kotdwara',
 'palanpur', 'tirunelveli', 'kozhikode', 'ibrahimpatnam', 'karaikal', 'malout',
 'bahadurgarh', 'dargamitta', 'khordha', 'kullu', 'bhiwani', 'gurdaspur',
 'malappuram', 'umbergaon', 'tirupati', 'panchkula', 'bhadrak', 'kanchipuram',
 'davangere', 'kelambakkam', 'darbhanga', 'banaskantha', 'pathankot',
 'adilabad', 'bahraich', 'palakkad', 'tiruchirappalli', 'samrala', 'chitrakoot',
 'chengalpattu', 'kadiri', 'dhar', 'hospet', 'pala', 'nabarangpur', 'neemrana',
 'kannur', 'dhampur', 'anantapur', 'dimapur', 'durg', 'rajsamand', 'perambalur',
 'barabanki', 'saharanpur (up)', 'rourkela', 'cuttack', 'sohna', 'ganjam',
 'saharsa', 'chhindwara', 'chalakudy', 'gautam buddha nagar', 'thoothukudi',
 'prakasam', 'phaltan', 'chikmagalur', 'roorkee', 'ichalkaranji', 'darjeeling',
 'sivasagar', 'silchar', 'brahmapuri', 'orai', 'tilakwadi', 'veraval',
 'dharmapuri', 'gajraula', 'nuzvid', 'ellenabad', 'east singhbhum', 'suri',
 'pithoragarh', 'bagru', 'goalpara', 'nalanda', 'jehanabad', 'darrang',
 'shikohabad', 'karimnagar', 'samastipur', 'abohar', 'howrah', 'hingoli',
 'kokrajhar', 'sant kabir nagar', 'uttara kannada', 'gohana', 'pondicherry',
 'panchmahal', 'sindhanur', 'gadag', 'ajmer', 'kotagiri', 'jalna', 'hassan',
 'chandrapur', 'anantnag', 'sheopur', 'mau', 'mirzapur', 'araria', 'katihar',
 'motihari', 'chitradurga', 'banga', 'athani', 'rishikesh', 'madhepura',
 'wardha', 'padra', 'gopalganj', 'almora', 'viluppuram', 'dindigul', 'margao',
 'kadapa', 'ponda', 'pandharpur', 'baharagora', 'nainital', 'bastar',
 'sultanpur', 'maharajganj', 'kushalanagar', 'belthangady', 'gadchiroli',
 'rajnandgaon', 'kalyani', 'kotma', 'karur', 'udhampur', 'jorhat', 'tarn taran',
 'murshidabad', 'bhayandar', 'cuddalore', 'chandausi', 'thanjavur', 'koriya',
 'siddipet', 'madhubani', 'khamgaon', 'nahan', 'kekri', 'erode', 'duliajan',
 'hoskote', 'west kameng', 'budgam', 'paonta sahib', 'kalol', 'anekal',
 'zamania', 'charkhi dadri', 'udupi', 'sangrur', 'nagole', 'kalahandi', 'imphal',
 'moga', 'abu road', 'perumbavoor', 'dasuya', 'batala', 'bhuj', 'kanjirappally',
 'chomu', 'pehowa', 'kangra', 'sivaganga', 'panaji', 'dera bassi', 'narsinghpur',
 'meham', 'nangal', 'karad', 'raichur', 'mahbubnagar', 'pilibhit', 'jalore',
 'barwani', 'seoni', 'hansi', 'mancherial', 'parvathipuram', 'tura',
 'cooch behar', 'sadabad', 'nuh', 'ranaghat', 'biaora', 'balasore', 'sundergarh',
 'shahbad', 'puttur', 'ashoknagar', 'rawatbhata', 'sabarkantha', 'bhawanipatna',
 'dharamshala', 'krishna', 'alappuzha', 'nabha', 'vidisha', 'ambegaon', 'kamrup',
 'pohir', 'mandya', 'beed', 'padrauna', 'tiruvallur', 'bihar sharif', 'rajpura',
 'shahad', 'doda', 'dausa', 'siwan', 'lower subansiri', 'murthal', 'nadiad',
 'hardoi', 'deoria', 'kendrapara', 'mandi gobindgarh', 'tapi', 'dadri', 'kathua',
 'vaijnath', 'jagadhri', 'modinagar', 'wagholi', 'sheohar', 'tumkur',
 'paratwada', 'poonamallee', 'karkala', 'ranni', 'thiruvalla', 'nimbahera',
 'bagaha'
])
Color = st.selectbox("Color", ['silver', 'grey', 'white', 'blue', 'silky silver', 'bakers chocolate',
 'cerulean blue', 'brown', 'nan', 'gray', 'prime pool side blue',
 'granite grey', 'other', 'arctic white', 'maroon', 'metallic glistening grey',
 'midnight plum', 'black', 'midnight black', 'magma grey', 'golden',
 'solid white', 'red', 'new granite grey', 'granite blackk', 'bright red',
 'glistening grey', 'superior white', 'dusky brown', 'metallic silky silver',
 'fiery red', 'typhoon silver', 'star dust', 'fire brick red', 'uptown red',
 'aqua teal', 'polar white', 'pearl arctic white', 'serene blue', 'yellow',
 'dark gray metallic', 'orange', 'linen beige', 'gold', 'imperial beige',
 'green', 'superior white avance edition', 'violet', 'pearl brown',
 'passion red', 'purple', 'ecru beige', 'poolside blue', 'titan grey',
 'tango orange', 'breeze blue', 'coral white', 'sleek silver', 'ember grey',
 'maharajah red', 'wine red', 'diamond black', 'o blue', 'pure white',
 'switch blade silver', 'caviar black', 'blazing red', 'topaz',
 'crystal white', 'pristine blue', 'berry red', 'olympic white',
 'sunfire yellow', 'diamond white', 'arctic silver', 'marine blue',
 'daytona grey', 'oceanic white', 'eco green', 'pearlescent white',
 'metal mustard', 'avant garde bronze', 'grey mica metallic',
 'ice cool white', 'bronze', 'garnet red', 'silver metallic', 'urban bronze',
 'arizona blue', 'blackisred', 'artic white', 'alabaster silver metallic',
 'prl. brave khaki', 'burgundy', 'pearl white', 'metallic magma grey',
 'moonlight silver', 'tungsten silver', 'electric blue', 'grey metallic',
 'carnelian red pearl', 'titanium grey', 'bronz', 'silver mica metallic',
 'quartz black', 'tafeta white', 'super white', 'brounze', 'summit white',
 'silky gold mica metallic', 'white pearl crystal shine', 'sandrift grey',
 'blue dark', 'night shade black', 'toreador red',
 'sparkling black crystal shine', 'b red', 'g red', 'dual tone top model',
 'blackish red', 'beige', 'glacier white pearl', 'military', 'cedar brown',
 'gold shimmer', 'mustard', 'others', 'carnekian red pearl',
 'white orchid pearl', 'golden brown metallica', 'metallic pearl blue blaze',
 'modern steel metalic', 'passion red solid', 'ice silver metallic',
 'power blue metallic', 'black sapphire', 'titanium silver',
 'luminous sand metallic', 'crystal white pearl metallic', 'onyx black',
 'ice white', 'ruby red', 'splash white', 'glacier white metallic',
 'obsidian black', 'brilliant blue metallic', 'osmium grey metallic',
 'cafe white', 'classic grey - etios', 'symphony silver', 'sunny white',
 'champagne mica metallic', 'classic grey', 'enticing silver',
 'phantom brown', 'inferno orange', 'champegne mica mettalic',
 'super white ii', 'vermilion red', 'suave silver', 'iconic grey',
 'groovy orange with sunny white roof', 'attitude black', 'insta blue',
 'sky blue', 'blue metallic', 'puple', 'planet grey', 'slate grey',
 'zanskar blue', 'metallic moonlight silver', 'metallic woodland brown',
 'cayenne orange', 'mettalic silver', 'woodland brown',
 'metal mustard with black roof', 'outback bronze', 'metallic graphite grey',
 'metallic blue', 'glacier white', 'pearl supreme white-adventure edition',
 'solid black', 'metallic fiery red', 'pearl supreme white', 'mahogany brown',
 'metallic red', 'cayenne-orange-body-with-mystery-black-roof', 'cool white',
 'moondust silver', 'absolute black', 'smoke grey', 'metallic grey',
 'mars red', 'canyon-ridge', 'sparkling gold', 'chill', 'sunset red',
 'moondust silver-ford ecosport', 'squeeze', 'white gold metallic',
 'chill metallic', 'colorado red', 'paprika red', 'panther black', 'sea grey',
 'platinum standrad', 'race red', 'c silver', 'kinetic blue-ford ecosport',
 'oxford white', 'daimond white', 'sky grey', 'golden white', 'smoke',
 'flash red', 'toffee brown', 'copper orange', 'candy white', 'reflex silver',
 'carbon steel', 'lapiz blue', 'shadow blue metallic', 'terra beige metallic',
 'deep black', 'reflex silver metallic', 'titanium beige',
 'toffee brown metallic', 'night blue', 'pepper grey', 'shadow blue',
 'flash red - volkswagen polo', 'r earth', 'l brown m',
 'oak brown - volkswagen passat', 'oryx white', 'cuppuccino beige',
 'cappuccino beige', 'quartz grey', 'magic black', 'honey orange',
 'brilliant silver', 'mato brown', 'silver gold', 'c beidge', 'brown/biege',
 'amethyst royal', 'black magic', 'r brunello', 'diamond silver',
 'met ecru beige', 'c beige', 'rio red', 'deep black pearl',
 'business grey metallic', 'lava blue', 'corrida red', 'race blue',
 'magnetic brown', 'storm blue', 'rosso brunello', 'light blue',
 'black magic pearl effect', 'satin grey', 'palladium silver', 'polar silver',
 'cirrus white', 'palladium silver metallic', 'jupiter red',
 'metallic obsidian black', 'designo diamond white bright',
 'metallic carneol red', 'obsidian black metallic', 'iridium silver',
 'calcite white', 'cosmos black', 'dolomite brown', 'cavansite blue',
 'iridium silver metallic', 'indium grey metallic', 'selenite grey metallic',
 'metallic iridium silver', 'designo hyacinth red metallic',
 'cuprite brown metallic', 'mojave silver', 'burnt coconut', 'super red',
 'green cocktail', 'sand drift grey', 'velvet red', 'misty lake',
 'burgundy red', 'rainforest green', 'platinum metallic', 'l beidge',
 'original colour', '?????', 'atlantis blue', 'cashmere',
 'misty lake metallic', 'bright green', 'poly silver', 'moonbeam white',
 'kandinsky red', 'melbourne red', 'mediterranean blue', 'mineral grey',
 'alpine white', 'mineral grey luxury-line variant', 'space grey',
 'imperial blue brillant effect', 'mineral white',
 'imperial blue brilliant effect luxury-line variant',
 'deep sea blue - bmw', 'estoril blue', 'blue stone mettalic', 'havanna',
 'mineral silver', 'phytonic blue', 'marrakesh brown', 'imperial blue',
 's grey', 'deep sea blue - bmw x1', 'sparkling brown metallic',
 'sparking brown metallic',
 'imperial blue brilliant effect prestige variant', 'deep sea blue',
 'glacier silver', 'midnight blue - bmw x1', 'bernina grey brilliant effect',
 'valencia orange', 'bluestone metallic', 'monaco blue', 'intense red',
 'gravity gray', 'aurora black pearl', 'steel silver', 'intelligence blue',
 'glacier white pearl with aurora black pearl', 'beige gold',
 'intense red with aurora black pearl', 'punchy orange',
 'beige gold with  aurora black pearl', 'floret silver metallic',
 'ibis white', 'cortina white', 'cobalt blue metallic', 'mythos black',
 'utopia blue', 'moonlight', 'mythos black metallic', 'scuba blue metallic',
 't brown', 'dakota grey metallic', 'teak brown metallic',
 'havanna black metallic', 'misano red', 'carrara white',
 'myth black metallic', 'firmament blue metallic',
 'phantom black pearl effect', 'monsoon grey', 'moonlight blue metallic',
 'arabian blue crystal effect', 'sunshine orange', 'storm white',
 'sand stone brawn', 'blade silver', 'sterling grey', 'b grey',
 'sandstone browns', 'turquoise blue', 'bronze grey', 'brick red', 's orange',
 'bgrey', 'pearl white with amber orange', 'fire red', 'sapphire blue',
 'vivid blue with strom white', 'sapphire black',
 'pearl white with onyx black', 'deep grey', 'night shade',
 'bronze grey - nissan sunny', 'fire red with onyx black', 'glaze red',
 'starry black', 'havana grey', 'agate red', 'aurora silver',
 'burgundy red metallic', 'candy white with starry black', 'starry sky blue',
 'warm white', 'metal ash', 'metal black', 'glaze red with starry black',
 'minimal grey', 'exotica red', 'brilliant black', 'granite crystal',
 'magenese grey', 'vocal white', 'hydro blue', 'techno metallic green',
 'galaxy blue', 'bright white', 'ruby', 'lime', 'vivid blue', 'tuscan wine',
 'hip hop black', 'oceanic blue', 'magnesio grey', 'furnace red', 't wine',
 'magnesium grey', 'formula red', 'bronzo tan', 'exotic red', 'loire blue',
 'firenze red', 'fuji white', 'santorini black', 'yulong white', 'dark blue',
 'magic blue metallic', 'rich java', 'black sapphire metallic', 't bronze',
 'caviar metallic', 'ultimate black metallic', 'polaris white', 'storm grey',
 'himalayan white', 'deep blue', 'pure black', 'iceberg silver',
 'opulent purple', 'satin white - rexton', 'volcano black', 'cosmic black',
 'silky white', 'blazin red', 'chili red', 'jet black metallic', 'mist silver',
 'fiery black', 'intense white', 'cumulus gray with black roof', 'stardust',
 'pearl met. arctic white', 'phantom black', 'tefeta white', 'taffeta white',
 'mint white', 'calgary white', 'premium silver metallic', 'alabaster silver',
 'metallic pearl arctic white', 'solid bright red', 'modern steel metallic',
 'aquamarine', 'porcelain white', 'twilight blue',
 'blazing red with midnight black', 'bold beige metallic',
 'golden brown metallic', 'crystal black pearl', 'urban titanium',
 'pearl snow white', 'orcus white', 'solid fire red', 'paradise blue',
 'rocky beige', 'avenue white', 'noble white', 'habanero red', 'downtown red',
 'platinum white pearl', 'lunar silver metallic', 'espresso brown',
 'alabaster silver metallic - honda city', 'nexa blue', 'premium silver',
 'denim blue', 'ray blue', 'bright silver',
 'twilight blue - hyundai grand i10', 'metallic azure grey',
 'metallic premium silver', 'pearl-white-body-with-mystery-black-roof',
 'caffeine brown', 'cavern grey', 'midnight blue', 'starry night',
 'foliage green', 'carnelian', 'passion orange', 'urban titanium metallic',
 'energetic blue - brio', 'etna orange', 's beige', 'premium amber',
 'platinum silver', 'napoli black', 'dazzling silver', 'red rage',
 'blue blaze', 'golden brown', 'atlas black', 'papaya orange', 'royal blue',
 'premium white pearl', 'oxford blue', 'glasgow grey', 'bold black',
 'oberon black with deep blue undertone', 'nutmeg brown', 'satin white',
 'few dew', 'vermont red', 'pearl metallic dignity brown', 'phoenix red',
 'dark grey', 'clear beige', 'starlight blue', 'rallye red',
 'alabaster silver metallic - amaze', 'metallic ozone blue',
 'majestic silver', 'metallic sovereign blue', 'metallic clear beige',
 'tinsel blue', 'polished metal metallic', 'buzz blue', 'sunlight copper',
 'u titanium', 'orchid white pearl', 'high street gold', 'pristine white',
 'royal ruby red', 'radiant red', 'blue black dual tone', 'gold satin',
 'dynamo red', 'rockey biege', 'stn black', 'midtown grey', 'thunder black',
 'dazzle blue', 'red black', 'grey noir', 'majestic blue', 'dsat silver',
 'teak blue', 'platinum white', 'new warm', 'metallic brown', 'gala red',
 'mariana blue', 'fiery red with black roof', 'astern black', 'damson purple',
 'metallic blazing red', 'meteoroid grey metallic', 'meteor silver',
 'sherwood brown', 'carnelian red', 'mica grey', 'jet silver',
 'titan gray metallic', 'gallant red', 'scooper', 'designer grey',
 'everest white', 'real earth', 'red mulberry', 'new blazing red',
 'pearl blue', 'cyan', 'golden grey', 'g brown', 's bronze', 'brave khaki',
 'metallic sunlight copper', 'carbon black', 'monarch red',
 'rediant red metallic', 'flamboyant red', 'metallic torque blue', 'm b',
 'basket brown', 'of white', 'artic silver', 'couper silver', 'sky',
 'red passion', 'red passion with phantom black', 'dusky brown - ertiga',
 'lightning blue', 'mojito green', 'magma gray', 'avant grade bronze',
 't blue', '?', 'calisto copper', 'highway red', 'serene bluish silver',
 'polar white dual tone', 'royal burgundy', 'moroccan blue', 'flame red',
 'black mica', 'gaming grey', 'kinetic blue', 'euro', 'thermisto gold',
 'cooper dazzle', 'diffused silver', 'pearl', 'stary night', 'vintage brown',
 'autumn orange', 'mixchar gray', 'torque blue', 'tuscan red', 'dew white',
 'camo green', 'lunar silver', 'spunky blue', 'uptown red/midnight black',
 'venetian red', 'egyptian blue', 'white gold', 'aqua marine', 'silky beige',
 'galaxy grey', 'new mystique red', 'pearl midnight black',
 'majestic blue mattlic', 'mahogany-brown-body-with-marble-ivory-roof',
 'golden orange', 'brawn', 'pink', 'begie', 'matelic blue', 'army colour',
 'champion gold', 'me beige', 'prime star gaze', 'met ecru',
 'pearl phoenix red', 'metallic midnight black', 'sizzling red',
 'new torque blue', 'sizzling red with midnight black roof', 'cave black',
 'solid sizzle orange', 'pearl metallic midnight blue', 'oyster blue',
 'midnight black - maruti swift dzire', 'pearl sangria red',
 'pearl metallic auburn red', 'avant bronze', 'navy blue', 'twilight bl',
 'mystic blue', 'taiga brown', 'aqua teal dual tone', 'mushroom', 'carnelianr',
 'radiant red metallic', 'deep sapphire blue', 'mystic copper',
 'fiery orange', 'dolphin grey', 'iceberg white', 'java brown', 'molten red',
 'oceanic black', 'sunshine yellow', 'pure silver', 'malabar silver',
 'calypso red', 'tropical mist', 'infinity black', 'spanish tan',
 'harbour blue', 'red and black', 'pacific blue', 'fiery yellow', 'urban blue',
 'mysterious violet', 'autumn orange and pearl arctic white', 'rust',
 'deep forest', 'thunder blue', 'blue onyx', 'red wine',
 'twilight blue - elantra', 'p metal m', 'brownish', 'm s metall',
 'nighthawk black', 'new warm silver', 'u.titanium', 'lakeprpl',
 'lake side brown', 'm copper', 'expresso brown', 'seattle silver',
 'salsa red', 'ivory white', 'foresta green', 'premium cosmo dark', 'deep red',
 'neo orange', 'spice red', 'artic silver - sumo grande', 'alp blue',
 'fiery yellow with pearl arctic white', 'bluish silver',
 'carbon bronze pearl', 'brilliant gold metallic', 'a3aqumarne', 'copper',
 'light sky blue', 'prime metallic brown', 'pearl metallic arctic white',
 'granite grey - sx4', 'cherry', '??????', 'twilight blue - santro',
 'sherbet blue', 'dual-tone red rage', 'dark wine colour', '????',
 'rockey beige', 'rust orange', 'lakeside brown', 'opera', 'cloudy gray',
 'biege', 'cherry red', 'earth brown', 'midnight grey', 'dynasty red'
])

Drive_Type = st.selectbox("Dirve Type", ['fwd', '2wd', 'rwd', 'awd', '4wd', '4x2'])
carType = st.selectbox("Car Type", ['corporate', 'partner', 'assured'])
owner_type = st.selectbox("Owner Type", ['first', 'second', 'third', 'fourth', 'fifth', 'unregistered car'])

data_df = pd.DataFrame([{
    "car_age": car_age,
    "km": km,
    "km_year": km_year,
    "marka_model": marka_model,
    "Length": Length,
    "Width": Width,
    "Height": Height,
    "Wheel Base": Wheel_Base,
    "Seats": Seats,
    "Max Power Delivered": Max_Power,
    "Max Torque Delivered": Max_Torque,
    "fuel": fuel,
    "transmission": transmission,
    "body": body,
    "City": City,
    "Color": Color,
    "Drive Type": Drive_Type,
    "carType": carType,
    "owner_type": owner_type
}])


if st.button("Predict"):
    pred_log = model.predict(data_df)
    pred_price = np.expm1(pred_log)[0]
    st.success(f"Estimated Price: {pred_price:.2f} INR")
